# Generated by Django 3.0.2 on 2022-01-03 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('code', models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Торговая марка (Бренд)',
                'verbose_name_plural': 'Торговые марки (Бренды)',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория (вид номенклатуры)',
                'verbose_name_plural': 'Категории (виды номенклатуры)',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=60, verbose_name='Наименование')),
                ('code', models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны мира (по ОКСМ)',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('code', models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=25, verbose_name='Наименование')),
                ('code', models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы (по ОКЕИ)',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('code', models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='Код')),
                ('art', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Артикул')),
                ('descriptions', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogapp.Brand', verbose_name='Марка (бренд)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogapp.Category', verbose_name='Вид номенклатуры')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogapp.Country', verbose_name='Страна происхождения')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogapp.Manufacturer', verbose_name='Производитель')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogapp.Unit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
