# Generated by Django 3.0.2 on 2022-01-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='uid',
            field=models.UUIDField(editable=False),
        ),
    ]
