# Generated by Django 3.0.2 on 2022-01-03 11:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0003_auto_20220103_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='uid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36),
        ),
    ]
