# Generated by Django 3.0.2 on 2022-01-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0004_auto_20220103_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='uid',
            field=models.CharField(blank=True, editable=False, max_length=36, null=True),
        ),
    ]
