# Generated by Django 3.0.2 on 2022-01-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0005_auto_20220103_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='uid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
