# Generated by Django 3.0.2 on 2022-01-03 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0007_auto_20220103_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='uid',
        ),
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
