# Generated by Django 3.0.2 on 2022-01-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0009_auto_20220103_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Торговая марка (Бренд)', 'verbose_name_plural': 'Торговые марки (Бренды)'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория (вид номенклатуры)', 'verbose_name_plural': 'Категории (виды номенклатуры)'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны мира (по ОКСМ)'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name'], 'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name'], 'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы (по ОКЕИ)'},
        ),
    ]
