# Generated by Django 3.0.2 on 2022-01-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0010_auto_20220105_1042'),
        ('catalogapp', '0010_auto_20220105_1250'),
    ]

    operations = [
    ]
