# Generated by Django 3.0.2 on 2022-01-06 05:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerapp', '0002_auto_20220106_0652'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('order_number', models.IntegerField(verbose_name='Номер заказа')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customerapp.Customer', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ покупателя',
                'verbose_name_plural': 'Заказы покупателей',
                'ordering': ['-order_date'],
            },
        ),
    ]
