# Generated by Django 3.0.2 on 2022-01-06 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0011_merge_20220106_0638'),
        ('orderapp', '0002_auto_20220106_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemorder',
            options={'ordering': ['item_number'], 'verbose_name': 'Строка заказа покупателя', 'verbose_name_plural': 'Строки заказов покупателей'},
        ),
        migrations.AddField(
            model_name='itemorder',
            name='item_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер строки'),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='orderapp.Order'),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogapp.Product', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='quant',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Всего'),
        ),
    ]
