# Generated by Django 3.0.2 on 2022-01-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_auto_20220106_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemorder',
            options={'ordering': ['item_number'], 'verbose_name': 'Строка заказа покупателя', 'verbose_name_plural': 'Строки заказа покупателя'},
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Всего'),
        ),
    ]
