# Generated by Django 3.0.2 on 2022-01-06 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_auto_20220106_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orderapp.Order'),
        ),
    ]
